### ISSUE TITLE
Core generated ...

### ISSUE THREAD

**Issue by VielLosero** [alariq/mc2#12]
I think i am close to run it but I need some help, please.
I am new compiling but i followed all the instructions and solved the errors, but...

`[v@arcadia build_mc2]$ ./mc2
Built-in video drivers: x11, wayland, KMSDRM, KMSDRM_LEGACY, dummy
Video driver: x11
SDL revision: hg-14525:e52d96ea04fc
We compiled against SDL version 2.0.14
But we are linking against SDL version 2.0.14.
Number of displays: 1
Display 0:
  Current mode: 1920x1080@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
      Red Mask   = 0x00ff0000
      Green Mask = 0x0000ff00
      Blue Mask  = 0x000000ff
  Fullscreen video modes:
    Mode 0: 1920x1080@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 1: 1920x1080@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 2: 1920x1080@40Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 3: 1680x1050@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 4: 1600x900@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 5: 1600x900@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 6: 1440x810@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 7: 1400x1050@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 8: 1400x900@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 9: 1368x768@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 10: 1280x1024@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 11: 1280x960@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 12: 1280x800@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 13: 1280x800@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 14: 1280x720@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 15: 1280x720@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 16: 1024x768@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 17: 1024x768@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 18: 1024x576@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 19: 1024x576@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 20: 960x720@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 21: 960x600@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 22: 960x540@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 23: 960x540@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 24: 928x696@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 25: 896x672@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 26: 864x486@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 27: 840x525@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 28: 800x600@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 29: 800x600@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 30: 800x600@56Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 31: 800x450@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 32: 720x405@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 33: 720x405@59Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 34: 700x525@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 35: 700x450@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 36: 684x384@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 37: 640x512@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 38: 640x480@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 39: 640x480@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 40: 640x400@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 41: 640x360@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 42: 640x360@60Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 43: 640x360@59Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 44: 512x384@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 45: 512x288@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 46: 480x270@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 47: 480x270@119Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 48: 432x243@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 49: 432x243@119Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 50: 400x300@121Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 51: 400x300@113Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 52: 360x202@119Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 53: 360x202@118Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 54: 320x240@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 55: 320x180@120Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
    Mode 56: 320x180@119Hz, 32 bits-per-pixel (SDL_PIXELFORMAT_RGB888)
        Red Mask   = 0x00ff0000
        Green Mask = 0x0000ff00
        Blue Mask  = 0x000000ff
Built-in render drivers:
  Renderer opengl:
    Flags: 0x0000000E (Accelerated | PresentVSync | 0x00000008)
    Texture formats (4): ARGB8888, ABGR8888, RGB888, BGR888
  Renderer opengles2:
    Flags: 0x0000000E (Accelerated | PresentVSync | 0x00000008)
    Texture formats (4): ARGB8888, ABGR8888, RGB888, BGR888
  Renderer software:
    Flags: 0x00000009 (0x00000001 | 0x00000008)
    Texture formats (8): ARGB8888, ABGR8888, RGBA8888, BGRA8888, RGB888, BGR888, RGB565, RGB555
Current Display Mode:
Screen BPP: 24

Vendor     : NVIDIA Corporation
Renderer   : GeForce GTX 960M/PCIe/SSE2
Version    : 4.0.0 NVIDIA 460.39
Extensions : (null)

SDL_GL_ACCELERATED_VISUAL: 1
SDL_GL_CONTEXT_MAJOR_VERSION: 4
SDL_GL_CONTEXT_MINOR_VERSION: 0
OpenGL Error: GL_INVALID_ENUM
Location : /home/v/data/meccomander_2/mc2/GameOS/gameos/utils/gl_utils.cpp : 379
/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:144: ERROR: Can't open shaders/gos_vertex.vert

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:302: ERROR: Shader filename: shaders/gos_vertex.vert, failed to load shader

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:144: ERROR: Can't open shaders/gos_tex_vertex.vert

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:302: ERROR: Shader filename: shaders/gos_tex_vertex.vert, failed to load shader

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:144: ERROR: Can't open shaders/gos_text.vert

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:302: ERROR: Shader filename: shaders/gos_text.vert, failed to load shader

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:144: ERROR: Can't open shaders/gos_vertex_lighted.vert

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:302: ERROR: Shader filename: shaders/gos_vertex_lighted.vert, failed to load shader

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:144: ERROR: Can't open shaders/gos_tex_vertex_lighted.vert

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:302: ERROR: Shader filename: shaders/gos_tex_vertex_lighted.vert, failed to load shader

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:144: ERROR: Can't open shaders/gos_vertex.vert

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:302: ERROR: Shader filename: shaders/gos_vertex.vert, failed to load shader

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:144: ERROR: Can't open shaders/gos_tex_vertex.vert

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:302: ERROR: Shader filename: shaders/gos_tex_vertex.vert, failed to load shader

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:144: ERROR: Can't open shaders/gos_text.vert

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:302: ERROR: Shader filename: shaders/gos_text.vert, failed to load shader

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:144: ERROR: Can't open shaders/gos_vertex_lighted.vert

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:302: ERROR: Shader filename: shaders/gos_vertex_lighted.vert, failed to load shader

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:144: ERROR: Can't open shaders/gos_tex_vertex_lighted.vert

/home/v/data/meccomander_2/mc2/GameOS/gameos/utils/shader_builder.cpp:302: ERROR: Shader filename: shaders/gos_tex_vertex_lighted.vert, failed to load shader

Opened audio at 22050 Hz 16 bit stereo (Little-Endian), 1024 bytes audio buffer
STATISTICS: [Quat Slerp Count : slerps]
STATISTICS: []
STATISTICS: [Mid Level Renderer]
STATISTICS: [==================]
STATISTICS: []
STATISTICS: [MLR Primitives : prims]
STATISTICS: [Indices/Vertices : Ratio]
STATISTICS: [Transformed vertices : vertices]
STATISTICS: [Number of alphasorted Tri : tri]
STATISTICS: [Lit vertices : vertices]
STATISTICS: [Unclipped vertices : vertices]
STATISTICS: [Clipped vertices : vertices]
STATISTICS: [Clip: Offscreen : Poly]
STATISTICS: [Clip: Onscreen : Poly]
STATISTICS: [Clip: One Plane : Poly]
STATISTICS: [Clip: > One Plane : Poly]
STATISTICS: []
STATISTICS: [gosFX]
STATISTICS: [=====]
STATISTICS: []
STATISTICS: [Points : prims]
STATISTICS: [Shards : prims]
STATISTICS: [Perts : prims]
STATISTICS: [Cards : prims]
STATISTICS: [Shapes : prims]
STATISTICS: [Profiles : prims]
STATISTICS: []
STATISTICS: [MechCommander 2 Texture Manager]
STATISTICS: [===============================]
STATISTICS: []
STATISTICS: [Handles Used : Handles]
STATISTICS: [Cache Misses : ]
STATISTICS: []
STATISTICS: []
Violación de segmento (`core' generado)
[v@arcadia build_mc2]$`

How i can solve or debug this?
Thanks

**Comment by alariq** [comment]
looks like it cannot find `shaders` folder.
from which folder are you running the game, it should be the same folder where `shaders` folder is located

**Comment by VielLosero** [comment]
Yes u right. I trying to run the game from the build folder. I copy it to mc2 and now the game run fine.
Thanks a lot. Great work.
