### ISSUE TITLE
Linux Start up

### ISSUE THREAD

**Issue by rpangrazio** [alariq/mc2#7]
I'm building on Ubuntu 16.04. 

So its entirely possible that I am being an idiot. I changed the line has the program look in ../FinalBuild for the data files to just ./ and copied the mc2 executable to the root directory of all the data, so it contains art, effects, movies, etc directories. But every time I start it, the SDL window opens than immediately closes. No information is really given, except the SDL video information. 

Any pointers to what I am doing wrong?

**Comment by rpangrazio** [comment]
Never mind, it seems that it was a version problem for the Open GL Shader Language

**Comment by alariq** [comment]
Can you elaborate a little bit on this? Maybe I can at least make a good error description or rewrite this part?

**Comment by rpangrazio** [comment]
Sorry about that. As a developer I should have known better.


Starting at line 221 in gameosmain.cpp:

const char* glsl_version = (const char*)glGetString(GL_SHADING_LANGUAGE_VERSION);
    SPEW(("GRAPHICS", "GLSL version supported: %s\n", glsl_version));

    int glsl_maj = 0, glsl_min = 0;
    sscanf(glsl_version, "%d.%d", &glsl_maj, &glsl_min);

    if(glsl_maj < 3 || (glsl_maj==3 && glsl_min < 30) ) {
        SPEW(("GRAPHICS", "Minimum required OpenGL version is 330 ES, current: %d.%d\n", glsl_maj, glsl_min));
        return 1;
    }

For some reason my system returns "FOREGROUND" from the glGetString call, probably my X11 setup. Looking at it now, it should report some kind of error, but I didn't see anything on the console.

**Comment by alariq** [comment]
Hmm, interesting )) I'll try to check it after vacation

**Comment by rpangrazio** [comment]
I'll see if I can get more info on my setup for you. I'm sure it has to do with that.
